repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: ^(infrastructure/terraform/.+\.yml|infrastructure/cloudformation/.+\.(yaml|yml)|examples/lambda_functions/serverless\.yml)$
      - id: check-json
        exclude: ^\.vscode/(glue-settings|simple-settings)\.json$
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements

  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
        exclude: >
          (?x)^(
            tests/test_wizards/test_interactive_wizard\.py|
            tests/test_wizards/test_run_interactive_wizard\.py|
            tests/test_wizards/test_init_project\.py|
            tests/test_aws/test_aws_mocking_example\.py|
            tests/unit/aws_mocking_examples/test_dynamodb_operations\.py|
            tests/unit/spark/test_transformations\.py|
            scripts/interactive_wizard\.py|
            scripts/project_health_dashboard\.py|
            scripts/init_project\.py|
            scripts/run_precommit\.py|
            scripts/tasks\.py|
            scripts/template_utils\.py|
            scripts/unified_setup\.py|
            examples/.*\.py|
            src/enterprise_data_engineering/common_utils/__init__\.py
          )$
      - id: ruff-format
        types_or: [python, pyi]
        exclude: >
          (?x)^(
            tests/test_wizards/test_interactive_wizard\.py|
            tests/test_wizards/test_run_interactive_wizard\.py|
            tests/test_wizards/test_init_project\.py|
            tests/test_aws/test_aws_mocking_example\.py|
            tests/unit/aws_mocking_examples/test_dynamodb_operations\.py|
            tests/unit/spark/test_transformations\.py|
            scripts/interactive_wizard\.py|
            scripts/project_health_dashboard\.py|
            scripts/init_project\.py|
            scripts/run_precommit\.py|
            scripts/tasks\.py|
            scripts/template_utils\.py|
            scripts/unified_setup\.py|
            examples/.*\.py
          )$

  # Security scanning
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        files: ^src/
        # Add specific excludes for CLI modules with subprocess calls that are reviewed and safe
        exclude: ^(src/enterprise_data_engineering/cli.*|src/enterprise_data_engineering/compat/__init__\.py|src/enterprise_data_engineering/examples/version_specific\.py)$

  # Markdown formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-footnote
        args: [--wrap=100]
        files: ^(docs|README\.md|.*\.md)$

  # Secret leak detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
        args: ["--config", ".gitleaks.toml"]
        exclude: ^\.secrets\.baseline$
        verbose: true

  # Terraform linting and validation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4
    hooks:
      - id: terraform_fmt
        verbose: true

      - id: terraform_validate
        args:
          - --hook-config=--recursive=false
        verbose: true

      - id: terraform_tflint
        files: ^infrastructure/terraform/
        args:
          - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"
          - "--args=--call-module-type=all"
          - "--hook-config=--recursive=true"
        verbose: true

  # JSON schema validation
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.3
    hooks:
      - id: check-github-workflows
      - id: check-dependabot

# CI configuration
ci:
  autofix_commit_msg: "[pre-commit.ci] Auto fixes from pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [terraform_validate, terraform_tflint, gitleaks, check-jsonschema]
  submodules: false
