AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for S3 data lake infrastructure"

Parameters:
  Environment:
    Description: Environment name (e.g., dev, test, prod)
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

  OrganizationName:
    Description: Organization name for resource naming
    Type: String
    Default: enterprise

  DataLakeName:
    Description: Name of the data lake
    Type: String
    Default: datalake

  RetentionDays:
    Description: Number of days to retain data in the data lake
    Type: Number
    Default: 365

Resources:
  # Raw data bucket (landing zone)
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${OrganizationName}-${DataLakeName}-raw-${Environment}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: !Ref RetentionDays
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: DataClassification
          Value: Confidential
        - Key: Layer
          Value: Raw

  # Processed data bucket (transformed data)
  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${OrganizationName}-${DataLakeName}-processed-${Environment}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: !Ref RetentionDays
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: DataClassification
          Value: Confidential
        - Key: Layer
          Value: Processed

  # Curated data bucket (analytics-ready data)
  CuratedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${OrganizationName}-${DataLakeName}-curated-${Environment}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: !Ref RetentionDays
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: DataClassification
          Value: Confidential
        - Key: Layer
          Value: Curated

  # Data Lake Bucket Policy
  DataLakeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RawDataBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyUnencryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub "${RawDataBucket.Arn}/*"
            Condition:
              StringNotEquals:
                "s3:x-amz-server-side-encryption": "AES256"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: !Sub "${RawDataBucket.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "false"

Outputs:
  RawDataBucketName:
    Description: Name of the raw data bucket
    Value: !Ref RawDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-RawDataBucketName"

  ProcessedDataBucketName:
    Description: Name of the processed data bucket
    Value: !Ref ProcessedDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-ProcessedDataBucketName"

  CuratedDataBucketName:
    Description: Name of the curated data bucket
    Value: !Ref CuratedDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-CuratedDataBucketName"
