# Example configuration for the Project Initialization System
# This file demonstrates the available configuration options

# Basic project information
project_name: my-awesome-project
package_name: my_awesome_project
description: A Python project with best practices built-in
version: 0.1.0

# Author information
author: Your Name
email: your.email@example.com
organization: Your Organization

# Project settings
license: MIT
python_version: "3.10"

# Dependencies
dependencies:
  - requests>=2.28.0
  - pyyaml>=6.0
  - click>=8.1.0

# Development dependencies
dev_dependencies:
  - pytest>=7.0.0
  - black>=22.3.0
  - isort>=5.10.0
  - mypy>=0.950
  - flake8>=4.0.0

# Git configuration
git:
  init: true
  remote: https://github.com/yourusername/my-awesome-project.git
  initial_branch: main

# CI/CD configuration
ci_cd:
  provider: github-actions
  enable_tests: true
  enable_linting: true
  enable_type_checking: true

# Documentation
documentation:
  format: mkdocs
  enable_api_docs: true

# Project structure customization
structure:
  src_layout: true
  include_tests: true
  include_docs: true
  include_examples: true
