name: CloudFormation CD

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/cloudformation/**'
      - '.github/workflows/cd-cloudformation.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint aws-sam-cli

      - name: Validate CloudFormation templates
        run: |
          cfn-lint infrastructure/cloudformation/**/*.yaml

  deploy-dev:
    needs: validate
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stacks
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/cloudformation/main.yaml \
            --stack-name enterprise-data-engineering-dev \
            --parameter-overrides Environment=dev \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --no-fail-on-empty-changeset

      - name: Update deployment status
        if: success()
        run: |
          echo "Deployment to development environment successful"

  deploy-prod:
    needs: deploy-dev
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stacks
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/cloudformation/main.yaml \
            --stack-name enterprise-data-engineering-prod \
            --parameter-overrides Environment=prod \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --no-fail-on-empty-changeset

      - name: Update deployment status
        if: success()
        run: |
          echo "Deployment to production environment successful"
