name: Dependency Security Scanning

on:
  push:
    branches: [main]
    paths:
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/dependency-security.yml'
  pull_request:
    branches: [main]
    paths:
      - 'pyproject.toml'
      - 'requirements*.txt'
  schedule:
    # Run weekly on Monday at 1AM
    - cron: '0 1 * * 1'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit safety
          pip install -e .

      - name: Run pip-audit scan
        run: pip-audit

      - name: Run safety check
        run: safety check

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          wait-for-processing: true
