name: Pre-commit Checks

on:
  push:
    branches: [main, dev, develop]
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Set up pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-

      - name: Run pre-commit on all files
        run: pre-commit run --all-files

      - name: Run pre-commit on changed files
        if: github.event_name == 'pull_request'
        run: |
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.base_ref }} HEAD)
          if [ -n "$CHANGED_FILES" ]; then
            echo "Checking changed files: $CHANGED_FILES"
            echo "$CHANGED_FILES" | xargs pre-commit run --files
